export default [
  {
    name: "Jordan 3 Retro",
    price: 3500,
    brand: "Jordan",
    image: "https://i.imgur.com/sIfJ9QZ.png",
    size: 26,
    gender: "Hombre",
  },
  {
    name: "Nike Dunk Low Retro",
    price: 3700,
    brand: "Nike",
    image: "https://i.imgur.com/Do3s0eq.png",
    size: 27,
    gender: "Hombre",
  },
  {
    name: "Puma LaMelo Ball MB.02",
    price: 4500,
    brand: "Puma",
    image: "https://i.imgur.com/ULt1o1S.png",
    size: 27.5,
    gender: "Hombre",
  },
  {
    name: "New Balance 1906D",
    price: 4500,
    brand: "New Balance",
    image: "https://i.imgur.com/Lj9CHOJ.png",
    size: 28,
    gender: "Hombre",
  },
  {
    name: "adidas Forum Low Bad Bunny",
    price: 3000,
    brand: "Adidas",
    image: "https://i.imgur.com/0jjgz69.png",
    size: 26.5,
    gender: "Hombre",
  },
  {
    name: "NikeCraft General Purpose Shoe",
    price: 3000,
    brand: "Nike",
    image: "https://i.imgur.com/2DsM7gU.png",
    size: 26.5,
    gender: "Hombre",
  },
  {
    name: "adidas Samba Vegan",
    price: 3000,
    brand: "Adidas",
    image: "https://i.imgur.com/83vsMPy.png",
    size: 26.5,
    gender: "Hombre",
  },
  {
    name: "Jordan 1 Retro High OG",
    model: "Taxi",
    price: 5000,
    brand: "Jordan",
    image: "https://i.imgur.com/vrt2F0z.png",
    size: 29,
    gender: "Hombre",
  },
  {
    name: "Nike LeBron 20",
    model: "All-Star",
    price: 5000,
    brand: "Nike",
    image: "https://i.imgur.com/yUT6hJ4.png",
    size: 30,
    gender: "Hombre",
  },
  {
    name: "Nike Air Force 1 Low SP",
    model: "AMBUSH Black",
    price: 6000,
    brand: "Nike",
    image: "https://i.imgur.com/CdVYGjo.png",
    size: 26.5,
    gender: "Hombre",
  },
  {
    name: "New Balance 2002R",
    model: "Protection Pack Rain Cloud",
    price: 5000,
    brand: "New Balance",
    image: "https://i.imgur.com/ZSeWNJv.png",
    size: 27,
    gender: "Hombre",
  },
  {
    name: "UGG Classic Ultra Mini",
    model: "Chestnut (W)",
    price: 5000,
    brand: "UGG",
    image: "https://i.imgur.com/zOW235Y.png",
    size: 27,
    gender: "Hombre",
  },
];
